#!/usr/bin/env bash
# The script displays "Best School" 9 times and print "Hi" on the 9th line

COUNT=1
while [ $COUNT -le 10 ]
do
	if [ $COUNT -eq 9 ]; then 
		echo "Hi"
	else
		echo "Best School"
	fi
	(( COUNT=COUNT+1 ))
done
