#!/usr/bin/env bash
# Script chamges the ip address of localhost and facebook
cp /etc/hosts ~/tempo
sed -i s/127.0.0.1/127.0.0.2/ ~/tempo
echo "8.8.8.8 facebook.com" >> ~/tempo
cp -f ~/tempo /etc/hosts
